project:
  type: website
  output-dir: docs

website:
  title: "STAT 311: Statistical Inference"
  favicon: img/chi2.png
  navbar:
    logo: img/chi2.png
    left:
      - file: index.qmd
        text: Home
      - file: schedule.qmd
        text: "Schedule"
      - file: homework.qmd
        text: "Homework"

    right:
      - icon: bar-chart-fill
        href: https://middlebury.instructure.com/

      
  sidebar:
    - title: "Schedule"
      style: "docked"
      contents:
        - schedule.qmd
        - weeks/week-01.qmd

  page-footer:
    center: |
      - ![Logo image](/img/middlebury.png){width=10%}

format:
  html:
    theme: 
      - united
      - customs.scss
    toc: false
    page-layout: article

    
editor: visual

