project:
  type: website
  output-dir: docs

website:
  title: "STAT 311: Statistical Inference"
  favicon: img/chi2.png
  navbar:
    logo: img/chi2.png
    left:
      - file: index.qmd
        text: Home
      - file: schedule.qmd
        text: "Schedule"
      - file: homework.qmd
        text: "Homework"
      - file: exam.qmd
        text: "Exams"
      - file: project.qmd
        text: "Final project"
    right:
      - icon: bar-chart-fill
        href: https://middlebury.instructure.com/

      
  sidebar:
    - title: "Schedule"
      style: "docked"
      contents:
        - schedule.qmd
        - weeks/week-01.qmd
        - weeks/week-02.qmd
        - weeks/week-03.qmd
        - weeks/week-04.qmd
        - weeks/week-05.qmd
        - weeks/week-06.qmd
        - weeks/week-07.qmd
        - weeks/week-08.qmd
        - weeks/week-09.qmd
        - weeks/week-10.qmd
        - weeks/week-11.qmd
        - weeks/week-12.qmd

        
  page-footer:
    center: |
      - ![Logo image](/img/middlebury.png){width=10%}

format:
  html:
    theme: 
      - united
      - customs.scss
    toc: false
    page-layout: article

    
editor: visual

